integration tests
mindbox-moscow/EasyCaching pull request #43
Opened 2022-01-22 13:10 UTC by SemenovaMasha

2022-01-24 10:29 UTC, Youkai-no-nii-chan requested changes
Проще все тесты вместе гонять и убрать разделение тестов на категории

2022-01-24 15:02 UTC, Youkai-no-nii-chan requested changes

2022-01-24 15:02 UTC, Youkai-no-nii-chan commented on test/EasyCaching.UnitTests/CachingTests/RedisCachingProviderTest.cs
> +                providerOptions.ConnectionString = TEST_REDIS_HOST + ":6380,allowAdmin=true";
Порт лучше добавить в TEST_REDIS_HOST.
А для порта 9999 выделить отдельную константу

2022-01-24 15:04 UTC, Youkai-no-nii-chan commented on test/EasyCaching.UnitTests/CachingTests/RedisCachingProviderTest.cs
> +                providerOptions.ConnectionString = TEST_REDIS_HOST + ":6380,allowAdmin=true";
Ну и лучше вынести эту константу в отдельный класс, так как она переиспользуется между разными тестами. Плюс по нашем код стайлу её назвать в UpperCamelCase

2022-01-24 15:12 UTC, Youkai-no-nii-chan commented on test/EasyCaching.UnitTests/CachingTests/RedisCachingProviderTest.cs
> +                providerOptions.ConnectionString = TEST_REDIS_HOST + ":6380,allowAdmin=true";
Пожалуй даже лучше вынести в отдельный класс не RedisHost, а AvailableRedis и другие ConnectionStrings

2022-01-25 17:42 UTC, SemenovaMasha commented
наверное пока так

2022-01-26 11:52 UTC, Youkai-no-nii-chan approved these changes

2022-01-26 11:52 UTC, Youkai-no-nii-chan commented on .github/workflows/pull-request.yml
> +      - name: Run integration tests
```suggestion
      - name: Run tests
```
Там же все тесты, а не только интеграционные

2022-01-26 11:52 UTC, Youkai-no-nii-chan commented on test/EasyCaching.UnitTests/TestHelpers/TestsRedisConstants.cs
> +        public static string GetAvailableRedisConnectionString(int? defaultDatabase = null) =>
```suggestion
        public static string GetAvailableRedisWithDatabase(int defaultDatabase) =>
```
Так понятнее, чем отличается AvailableRedis от этого метода

2022-01-26 17:27 UTC, merged