Обновляю драйвер редиса
mindbox-moscow/EasyCaching pull request #76
Opened 2022-09-05 15:11 UTC by korchak-aleksandr

продолжение https://github.com/mindbox-moscow/Mindbox.Framework/pull/2410

2022-09-05 15:13 UTC, Youkai-no-nii-chan approved these changes

2022-09-05 15:15 UTC, Youkai-no-nii-chan requested changes
Надо еще и версию

2022-09-05 15:15 UTC, Youkai-no-nii-chan commented on src/EasyCaching.Redis/EasyCaching.Redis.csproj
> +    <PackageReference Include="StackExchange.Redis" Version="2.6.48" />
Надо еще версию обновить чисто для этой либы - `<PackageVersion>3.6.1</PackageVersion>`

2022-09-05 15:54 UTC, korchak-aleksandr commented on src/EasyCaching.Redis/EasyCaching.Redis.csproj
> +    <PackageReference Include="StackExchange.Redis" Version="2.6.48" />
ты имеешь ввиду NeoSmart.AsyncLock?

2022-09-05 16:00 UTC, korchak-aleksandr commented on src/EasyCaching.Redis/EasyCaching.Redis.csproj
> +    <PackageReference Include="StackExchange.Redis" Version="2.6.48" />
по ней я кстати не вижу апдейтов

2022-09-05 16:01 UTC, korchak-aleksandr commented on src/EasyCaching.Redis/EasyCaching.Redis.csproj
> +    <PackageReference Include="StackExchange.Redis" Version="2.6.48" />
а хотя я понял о чем ты, поднять версию общую пакетов. ща сделаю

2022-09-05 16:09 UTC, korchak-aleksandr commented on src/EasyCaching.Redis/EasyCaching.Redis.csproj
> +    <PackageReference Include="StackExchange.Redis" Version="2.6.48" />
поставил 3.6.2 аналогично другим пакетам

2022-09-05 16:48 UTC, listerenko approved these changes

2022-09-06 07:41 UTC, Youkai-no-nii-chan approved these changes

2022-09-06 08:01 UTC, merged